export const BOARDS = 'BOARDS';
export const DICTIONARIES = 'DICTIONARIES';
export const LOADER = 'FLAGS/LOADER';
export const LOGGED = 'FLAGS/LOGGED';
export const ERROR_MESSAGE = 'ERRORS/ERROR_MESSAGE';
export const ERROR_VALIDATION = 'ERRORS/ERROR_VALIDATION';